name: Python Auto Refactor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake autopep8 flake8 pyupgrade

      - name: Run Black (format code)
        run: black .

      - name: Run isort (sort imports)
        run: isort .

      - name: Run autoflake (remove unused imports)
        run: autoflake --in-place --remove-all-unused-imports --recursive .

      - name: Run autopep8 (fix style)
        run: autopep8 --in-place --aggressive --aggressive -r .

      - name: Run flake8 (lint)
        run: |
          flake8 . || echo "flake8 warnings found"

      - name: Show git diff
        run: git diff

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --quiet || git commit -m "Auto-refactor: format, lint, and modernize python code"
        continue-on-error: true

      - name: Push changes
        if: github.event_name == 'push'
        run: git push
        continue-on-error: true
